# Generated by Django 4.0.3 on 2022-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_bookings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
